name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**/Cargo.toml'
      - '**.rs'
  pull_request:
    branches:
      - main
    paths:
      - '**/Cargo.toml'
      - '**.rs'
  merge_group:
    types: [checks_requested]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    name: Check (${{ matrix.check.name }})
    strategy:
      matrix:
        check:
          - { name: rustfmt, cmd: cargo fmt --check }
          - { name: clippy, cmd: cargo clippy --all-targets --all-features -- -D warnings }
          - { name: docs, cmd: cargo doc --all-features }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: moonrepo/setup-rust@v1
        with:
          channel: nightly
          components: rustfmt, clippy

      - name: Run
        env:
          RUSTDOCFLAGS: -D warnings
        run: ${{ matrix.check.cmd }}

  test:
    name: Test (${{ matrix.rust.name }})
    needs:
      - checks
    strategy:
      matrix:
        rust:
          - { name: stable, version: stable }
          - { name: nightly, version: nightly }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: moonrepo/setup-rust@v1
        with:
          channel: ${{ matrix.rust.version }}

      - name: Test
        run: cargo test --all-features
        timeout-minutes: 5
