name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**/Cargo.toml'
      - '**.rs'
  pull_request:
    branches:
      - main
    paths:
      - '**/Cargo.toml'
      - '**.rs'
  merge_group:
    types: [checks_requested]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: moonrepo/setup-rust@v1
        with:
          channel: nightly
          components: rustfmt, clippy

      - name: Check rustfmt
        run: cargo fmt --check

      - name: Check clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Check docs
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --all-features

  test:
    name: Test (${{ matrix.rust.name }})
    needs:
      - checks
    strategy:
      matrix:
        rust:
          - { name: stable, version: stable }
          - { name: nightly, version: nightly }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: moonrepo/setup-rust@v1
        with:
          channel: ${{ matrix.rust.version }}

      - name: Test
        run: cargo test --all-features
        timeout-minutes: 5
